### ISSUE TITLE
A task that is really important

### ISSUE THREAD

**Issue by kasparvonbeelen** [kasparvonbeelen/training-20190328#1]

**Comment by mcollardanuy** [comment]
@kasparvonbeelen, do this today.

**Comment by kasparvonbeelen** [comment]
@mcollardanuy will reassign to milestone Morregen!

**Comment by mcollardanuy** [comment]
I close this because I all the time think I have this really important task pending!

**Comment by kasparvonbeelen** [comment]
Sure (even though I still think it is very important) 😉
